[Service]
Environment=PPD_PATHS=/var/lib/legacy-printer-app/ppd:/usr/share/cups/model:/usr/lib/cups/driver
ExecStart=
ExecStart=legacy-printer-app server -o log-level=debug -o backend-directory=/usr/local/libexec/konica-backend
ExecStartPost=/usr/local/bin/ensure-konica206uri.sh
