#!/bin/bash
# ensure-konica206uri.sh (generated by install-konica-anylinux.sh)
URI='cups:usb://KONICA%20MINOLTA/206?serial=A8A6041029423&interface=1'
DRIVER='konica-minolta--206--full-bleed-retrofit-en'
IPP='ipp://localhost:8000/ipp/print/konica206uri'
PPD='/var/lib/legacy-printer-app/ppd/konica206-pdf-fullbleed.ppd'
# ensure 245igdirf.ocm config is resolvable alongside the filter (runs every invocation)
OCM_SRC=/usr/local/lib/konica/KonicaMinolta/245igdi/Filters/mtorf.ocm
OCM_DST=/usr/lib/cups/filter/KonicaMinolta/245igdi/Filters/mtorf.ocm
if [ -f "$OCM_SRC" ]; then
  [ -f "$OCM_DST" ] || cp -f "$OCM_SRC" "$OCM_DST"
  # force the symlink absolute so it survives a relative-symlink reinstall
  ln -sf "$OCM_SRC" /usr/lib/cups/filter/KonicaMinolta/245igdi/Filters/245igdirf.ocm
fi
# ensure CUPS queues exist (guarded; lpadmin -P is unsupported on CUPS 3.0)
if command -v lpadmin >/dev/null 2>&1 && command -v lpstat >/dev/null 2>&1; then
  # primary: PPD-less IPP queue (CUPS 3.0-ready default)
  if ! lpstat -p konica206uri >/dev/null 2>&1; then
    lpadmin -p konica206uri -v "$IPP" -E 2>/dev/null || true
    lpadmin -d konica206uri 2>/dev/null || true
  fi
  # optional: classic PPD queue so GTK/Atril offers Duplex on CUPS 2.x
  # (silently skipped on CUPS 3.0 where -P is unsupported)
  if ! lpstat -p konica206uri-ppd >/dev/null 2>&1; then
    lpadmin -p konica206uri-ppd -v "$IPP" -P "$PPD" -E 2>/dev/null || true
    lpadmin -p konica206uri-ppd -o sides-default=one-sided 2>/dev/null || true
  fi
fi
for i in $(seq 1 30); do
  if legacy-printer-app printers 2>/dev/null | grep -q '^konica206uri$'; then
    exit 0
  fi
  sleep 1
done
legacy-printer-app delete -d konica206uri 2>/dev/null
legacy-printer-app add -d konica206uri -v "$URI" -m "$DRIVER" 2>&1
if legacy-printer-app printers 2>/dev/null | grep -q '^konica206uri$'; then
  if [ -f "/usr/local/share/konica206uri/set-media-default.test" ]; then
    ipptool -tv "http://localhost:8000/ipp/print/konica206uri"       "/usr/local/share/konica206uri/set-media-default.test" >/dev/null 2>&1
  fi
  exit 0
fi
exit 1
